import type { AppContentData } from "@/types/appContent";

export const DEFAULT_APP_CONTENT: AppContentData = {
  version: 2,
  heroes: [
    { country: "uganda", title: "Ebyo eby'ewaka.", tagline: "Tastes of home, delivered to you in the UAE.", imageKey: "hero-uganda" },
    { country: "kenya", title: "Ladha ya nyumbani.", tagline: "The flavors of home, wherever you are.", imageKey: "hero-kenya" },
    { country: "ethiopia", title: "Ye ina bet t'aam.", tagline: "Bringing the taste of home to the Gulf.", imageKey: "hero-ethiopia" },
    { country: "other", title: "Africa's Finest.", tagline: "Every taste of the continent, in one place.", imageKey: "hero-pan-african" },
    { country: "all", title: "One App. Every African Kitchen.", tagline: "The whole continent, delivered to your door.", imageKey: "hero-pan-african" },
  ],
  baskets: [
    { id: "ugb1", country: "uganda", name: "Matooke Cook-Up", tagline: "Everything for a Sunday matooke feast", items: ["Matooke x2", "Groundnut Paste", "Sukuma Wiki", "Cassava Flour"], price: 59, currency: "AED", cardColor: "#4A7A32", lifestyleImageKey: "lifestyle-matooke", active: true, order: 1 },
    { id: "ugb2", country: "uganda", name: "Ugandan Family Feast", tagline: "Feed the family, feel at home", items: ["Posho 2kg", "Matooke x3", "G-Nut Soup Mix", "Chili Sauce", "Sukuma x2"], price: 89, currency: "AED", cardColor: "#8B5E3C", lifestyleImageKey: "lifestyle-ugali", active: true, order: 2 },
    { id: "ugb3", country: "uganda", name: "Weekend Rolex Kit", tagline: "Roll it up the Ugandan way", items: ["Rolex Spice Mix", "Sukuma Wiki", "Groundnut Paste", "Cassava Flour"], price: 42, currency: "AED", cardColor: "#C4A24A", lifestyleImageKey: "lifestyle-spices", active: true, order: 3 },
    { id: "keb1", country: "kenya", name: "Kenyan Family Ugali Kit", tagline: "The complete Kenyan dinner, always", items: ["Unga 2kg", "Sukuma Wiki x2", "Royco Mchuzi Mix", "Blue Band"], price: 49, currency: "AED", cardColor: "#4A7A32", lifestyleImageKey: "lifestyle-ugali", active: true, order: 1 },
    { id: "keb2", country: "kenya", name: "Chai & Chapati Bundle", tagline: "Morning rituals, never missed", items: ["Kenyan Chai Masala", "Blue Band", "Unga 1kg", "Royco Mix"], price: 41, currency: "AED", cardColor: "#8B4513", lifestyleImageKey: "lifestyle-coffee", active: true, order: 2 },
    { id: "keb3", country: "kenya", name: "Nyama Choma Night", tagline: "For when you need that smoky taste", items: ["Pilau Masala", "Royco Mchuzi Mix", "Githeri Mix", "Chai Masala"], price: 37, currency: "AED", cardColor: "#8B3A2A", lifestyleImageKey: "lifestyle-spices", active: true, order: 3 },
    { id: "etb1", country: "ethiopia", name: "Coffee Ceremony Kit", tagline: "The full Ethiopian coffee ritual", items: ["Ethiopian Coffee 250g", "Tej Honey Mix", "Teff Flour"], price: 79, currency: "AED", cardColor: "#3D1C0A", lifestyleImageKey: "lifestyle-coffee", active: true, order: 1 },
    { id: "etb2", country: "ethiopia", name: "Tibs Weekend Feast", tagline: "Sizzling tibs, just like Addis", items: ["Berbere x2", "Niter Kibbeh", "Mitmita", "Shiro Powder", "Injera x5"], price: 89, currency: "AED", cardColor: "#8B3A1A", lifestyleImageKey: "lifestyle-injera", active: true, order: 2 },
    { id: "etb3", country: "ethiopia", name: "Injera Starter Pack", tagline: "Make injera from scratch", items: ["Teff Flour 1kg", "Shiro Powder", "Berbere", "Niter Kibbeh"], price: 67, currency: "AED", cardColor: "#8B6914", lifestyleImageKey: "lifestyle-spices", active: true, order: 3 },
    { id: "afb1", country: "other", name: "West African Jollof Night", tagline: "Make the jollof everyone talks about", items: ["Jollof Spice Mix", "Suya Spice", "Palm Oil", "Plantain x2"], price: 49, currency: "AED", cardColor: "#C04020", lifestyleImageKey: "lifestyle-spices", active: true, order: 1 },
    { id: "afb2", country: "other", name: "Pan-African Feast", tagline: "A taste of the whole continent", items: ["Egusi", "Fufu Flour", "Ogbono Seeds", "Stockfish", "Palm Oil"], price: 79, currency: "AED", cardColor: "#3A6B2A", lifestyleImageKey: "hero-pan-african", active: true, order: 2 },
    { id: "afb3", country: "other", name: "African Pantry Staples", tagline: "Never run out of the essentials", items: ["Fufu Flour x2", "Jollof Spice x2", "Palm Oil", "Stockfish"], price: 62, currency: "AED", cardColor: "#6B3A1A", lifestyleImageKey: "lifestyle-spices", active: true, order: 3 },
  ],
  meals: [
    {
      id: "meal-ugali", country: "all", lifestyleImageKey: "lifestyle-ugali",
      name: "Ugali & Sukuma Wiki", description: "The ultimate Kenyan and East African comfort meal — dense maize porridge paired with sauteed collard greens.",
      prepTime: "10 min", cookTime: "25 min", servings: 4,
      ingredients: ["2 cups maize flour (unga)", "4 cups water", "1 tsp salt", "1 bunch sukuma wiki (collard greens), chopped", "1 medium onion, diced", "2 tomatoes, chopped", "2 tbsp cooking oil", "Salt and pepper to taste"],
      steps: ["Bring 4 cups of water to a boil in a heavy pot. Add salt.", "Gradually add maize flour while stirring constantly to avoid lumps.", "Reduce heat and stir vigorously until the ugali is thick and pulls away from the pot sides. Cook 8-10 min.", "For sukuma wiki: heat oil in a pan, fry onion until golden, add tomatoes and cook 3 min.", "Add chopped sukuma wiki and stir-fry on high heat for 5-7 min. Season and serve with ugali."],
      tip: "The key to smooth ugali is continuous stirring. Never stop moving it once the flour hits the water.",
      active: true, order: 1,
    },
    {
      id: "meal-injera", country: "ethiopia", lifestyleImageKey: "lifestyle-injera",
      name: "Ethiopian Injera Spread", description: "The centrepiece of Ethiopian dining — spongy teff flatbread loaded with vibrant stews and salads.",
      prepTime: "5 min (+ 2 days ferment)", cookTime: "30 min", servings: 4,
      ingredients: ["2 cups teff flour", "2.5 cups warm water", "1/2 tsp salt", "Berbere spice for stews", "Lentils, chickpeas, or meat for toppings"],
      steps: ["Mix teff flour with warm water until smooth. Cover and ferment at room temperature for 48 hours.", "When bubbles form and it smells slightly sour, it is ready.", "Heat a non-stick skillet on medium-high. Pour batter in a spiral, starting from outside in.", "Cover and cook 2-3 minutes until surface is dry and edges lift. Do not flip.", "Serve immediately with tibs, shiro, or lentil stew on top."],
      tip: "Use ready-made injera from Mekazon for speed — fermentation takes 2 days at home.",
      active: true, order: 2,
    },
    {
      id: "meal-matooke", country: "uganda", lifestyleImageKey: "lifestyle-matooke",
      name: "Ugandan Matooke Feast", description: "A Sunday staple across Uganda — steamed green cooking bananas wrapped in banana leaves and served with groundnut stew.",
      prepTime: "20 min", cookTime: "45 min", servings: 6,
      ingredients: ["6-8 green cooking bananas (matooke)", "Banana leaves for wrapping", "2 cups groundnut paste", "1 onion, chopped", "3 tomatoes, chopped", "2 cups water", "Salt to taste", "2 tbsp cooking oil"],
      steps: ["Peel matooke and wrap tightly in banana leaves. Place in a sufuria with a little water at the bottom.", "Steam on medium heat for 40-45 minutes until soft. Mash gently inside the leaves.", "For groundnut stew: fry onion in oil until golden, add tomatoes and cook 5 min.", "Add groundnut paste and water, stir well. Simmer 15 min until thick and fragrant.", "Unwrap matooke and serve with the groundnut stew poured over."],
      tip: "If banana leaves are unavailable, aluminium foil works — but the banana leaf imparts a subtle earthy flavour.",
      active: true, order: 3,
    },
    {
      id: "meal-coffee", country: "ethiopia", lifestyleImageKey: "lifestyle-coffee",
      name: "Ethiopian Coffee Ceremony", description: "The most important social ritual in Ethiopia — three rounds of coffee, roasted and brewed fresh.",
      prepTime: "10 min", cookTime: "30 min", servings: 4,
      ingredients: ["Ethiopian single-origin coffee beans (whole)", "Jebena (Ethiopian coffee pot) or French press", "Frankincense incense (optional)", "Sugar to taste", "Tena Adam leaves (optional herb)"],
      steps: ["Rinse the green beans and pan-roast over medium heat, stirring continuously for 10-15 min until dark brown.", "Grind the roasted beans finely using a wooden mortar or grinder.", "Bring water to a boil in the jebena. Add ground coffee and reduce heat. Simmer 5-10 min.", "Pour through a fine strainer into small handleless cups (cini).", "Serve in three rounds — Abol (first), Tona (second), Baraka (third, the blessing)."],
      tip: "The ceremony is as important as the coffee. Sit, relax, and share it with people you love.",
      active: true, order: 4,
    },
    {
      id: "meal-spices", country: "all", lifestyleImageKey: "lifestyle-spices",
      name: "African Spice Selection", description: "Build your spice pantry with the most essential African flavour bases — each one unlocks a dozen dishes.",
      prepTime: "5 min", cookTime: "0 min", servings: 1,
      ingredients: ["Berbere (Ethiopian chili blend)", "Suya spice (West African groundnut blend)", "Pilau masala (Kenyan aromatic blend)", "Royco Mchuzi Mix (East African all-purpose)", "Palm oil (West African cooking base)"],
      steps: ["Berbere — use as a marinade, stew base, or dry rub for meats.", "Suya spice — coat skewered meat or chicken. Grill over high heat.", "Pilau masala — toast in oil first, then add rice, onion, and meat for Kenyan pilau.", "Royco Mchuzi — stir into stews, soups, or bean dishes for depth.", "Palm oil — heat until liquid and use as the cooking fat for West African soups."],
      tip: "Store spices in sealed glass jars away from heat and light. They last up to 12 months.",
      active: true, order: 5,
    },
  ],
  categories: [
    { id: "cat-ug-1", country: "uganda", name: "Staples", icon: "nutrition", keywords: ["posho", "flour", "maize", "cassava", "groundnut", "unga", "matooke", "sukuma"], active: true, order: 1 },
    { id: "cat-ug-2", country: "uganda", name: "Grains", icon: "leaf", keywords: ["grain", "maize", "cassava flour", "millet", "sorghum", "wheat", "rice"], active: true, order: 2 },
    { id: "cat-ug-3", country: "uganda", name: "Spices", icon: "color-palette", keywords: ["spice", "rolex", "seasoning", "blend", "sauce", "chili", "paste", "soup mix"], active: true, order: 3 },
    { id: "cat-ug-4", country: "uganda", name: "Ready Food", icon: "fast-food", keywords: ["ready", "kit", "meal", "instant", "prepared"], active: true, order: 4 },
    { id: "cat-ke-1", country: "kenya", name: "Staples", icon: "nutrition", shopifyCollectionHandle: "kenyan-foodstuff", keywords: ["unga", "flour", "maize", "posho", "blue band", "margarine", "butter", "dairy"], active: true, order: 1 },
    { id: "cat-ke-2", country: "kenya", name: "Grains", icon: "leaf", keywords: ["grain", "wheat", "rice", "millet", "sorghum", "barley", "flour"], active: true, order: 2 },
    { id: "cat-ke-3", country: "kenya", name: "Spices", icon: "color-palette", keywords: ["spice", "royco", "mchuzi", "masala", "pilau", "blend", "seasoning", "chai"], active: true, order: 3 },
    { id: "cat-ke-4", country: "kenya", name: "Ready Food", icon: "fast-food", keywords: ["ready", "kit", "meal", "instant", "prepared", "githeri", "mix"], active: true, order: 4 },
    { id: "cat-et-1", country: "ethiopia", name: "Staples", icon: "nutrition", keywords: ["teff", "injera", "shiro", "niter", "kibbeh", "berbere", "butter", "oil"], active: true, order: 1 },
    { id: "cat-et-2", country: "ethiopia", name: "Grains", icon: "leaf", keywords: ["grain", "teff", "flour", "barley", "wheat", "corn", "sorghum", "millet"], active: true, order: 2 },
    { id: "cat-et-3", country: "ethiopia", name: "Spices", icon: "color-palette", keywords: ["spice", "berbere", "mitmita", "blend", "pepper", "chili", "powder", "coffee"], active: true, order: 3 },
    { id: "cat-et-4", country: "ethiopia", name: "Ready Food", icon: "fast-food", keywords: ["ready", "injera", "fresh", "kit", "meal", "instant", "prepared"], active: true, order: 4 },
    { id: "cat-ot-1", country: "other", name: "Staples", icon: "nutrition", keywords: ["fufu", "palm oil", "stockfish", "plantain", "yam", "cassava", "egusi", "ogbono"], active: true, order: 1 },
    { id: "cat-ot-2", country: "other", name: "Grains", icon: "leaf", keywords: ["grain", "fufu", "flour", "cassava", "plantain", "yam", "maize", "rice"], active: true, order: 2 },
    { id: "cat-ot-3", country: "other", name: "Spices", icon: "color-palette", keywords: ["spice", "suya", "jollof", "seasoning", "blend", "pepper", "ogiri"], active: true, order: 3 },
    { id: "cat-ot-4", country: "other", name: "Ready Food", icon: "fast-food", keywords: ["ready", "kit", "meal", "instant", "prepared", "mix"], active: true, order: 4 },
    { id: "cat-al-1", country: "all", name: "Staples", icon: "nutrition", keywords: ["unga", "posho", "cassava", "matooke", "fufu", "teff", "flour", "blue band", "palm oil"], active: true, order: 1 },
    { id: "cat-al-2", country: "all", name: "Grains", icon: "leaf", keywords: ["grain", "maize", "wheat", "teff", "millet", "rice", "sorghum", "barley", "cassava flour"], active: true, order: 2 },
    { id: "cat-al-3", country: "all", name: "Spices", icon: "color-palette", keywords: ["spice", "berbere", "pilau", "royco", "suya", "jollof", "mitmita", "blend", "seasoning"], active: true, order: 3 },
    { id: "cat-al-4", country: "all", name: "Ready Food", icon: "fast-food", keywords: ["ready", "kit", "meal", "instant", "prepared", "mix", "injera"], active: true, order: 4 },
  ],
};
